from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

from app.agent.prompts import build_system_prompt
from app.agent.tools import get_run_sql_tool
from app.core.config import get_settings
from app.core.duckdb_engine import get_duckdb_engine


def _fallback_answer(question: str, dataset_id: str) -> dict[str, str]:
    text = question.lower()
    if "how many rows" in text or "row count" in text:
        sql = "SELECT COUNT(*) AS row_count FROM {dataset}"
    else:
        sql = "SELECT * FROM {dataset} LIMIT 10"

    settings = get_settings()
    engine = get_duckdb_engine(settings.uploads_dir)
    rows = engine.run_sql(dataset_id=dataset_id, query=sql)
    return {
        "answer": str(rows),
        "sql": sql,
    }


def ask_dataset(question: str, dataset_id: str) -> dict[str, str]:
    settings = get_settings()
    engine = get_duckdb_engine(settings.uploads_dir)
    dataset = engine.get_dataset(dataset_id)

    if not settings.openai_api_key:
        return _fallback_answer(question=question, dataset_id=dataset_id)

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", build_system_prompt(dataset)),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
        ]
    )

    llm = ChatOpenAI(api_key=settings.openai_api_key, model="gpt-4o-mini", temperature=0)
    tools = [get_run_sql_tool()]
    agent = create_tool_calling_agent(llm=llm, tools=tools, prompt=prompt)
    executor = AgentExecutor(agent=agent, tools=tools, verbose=False)
    result = executor.invoke({"input": question})
    return {
        "answer": str(result.get("output", "")),
        "sql": "Generated by agent via run_sql tool",
    }
