from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

from app.agent.prompts import build_system_prompt
from app.agent.tools import (
    get_make_chart_tool,
    get_run_python_tool,
    get_run_sql_tool,
    make_chart,
    run_python,
)
from app.core.config import get_settings
from app.core.duckdb_engine import get_duckdb_engine


def _fallback_answer(question: str, dataset_id: str) -> dict[str, str]:
    text = question.lower()
    if "run_python" in text or "python" in text:
        python_code = (
            "result = int(df['quantity'].sum()) "
            "if 'quantity' in df.columns else len(df)"
        )
        answer = run_python(code=python_code, dataset_id=dataset_id)
        return {"answer": answer, "sql": "run_python fallback"}

    if "make_chart" in text or "chart" in text or "plotly" in text:
        settings = get_settings()
        engine = get_duckdb_engine(settings.uploads_dir)
        rows = engine.run_sql(
            dataset_id=dataset_id,
            query=(
                "SELECT category, SUM(quantity) AS total_quantity "
                "FROM {dataset} GROUP BY category ORDER BY total_quantity DESC"
            ),
        )
        chart_spec = {
            "data": [
                {
                    "type": "bar",
                    "x": [row["category"] for row in rows],
                    "y": [row["total_quantity"] for row in rows],
                }
            ],
            "layout": {"title": "Quantity by Category"},
        }
        answer = make_chart(spec=str(chart_spec))
        return {"answer": answer, "sql": "make_chart fallback"}

    if "how many rows" in text or "row count" in text:
        sql = "SELECT COUNT(*) AS row_count FROM {dataset}"
    else:
        sql = "SELECT * FROM {dataset} LIMIT 5"

    settings = get_settings()
    engine = get_duckdb_engine(settings.uploads_dir)
    rows = engine.run_sql(dataset_id=dataset_id, query=sql)
    return {
        "answer": str(rows),
        "sql": sql,
    }


def ask_dataset(question: str, dataset_id: str) -> dict[str, str]:
    settings = get_settings()
    engine = get_duckdb_engine(settings.uploads_dir)
    dataset = engine.get_dataset(dataset_id)

    if not settings.openai_api_key:
        return _fallback_answer(question=question, dataset_id=dataset_id)

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", build_system_prompt(dataset)),
            ("human", "{input}"),
            ("placeholder", "{agent_scratchpad}"),
        ]
    )

    llm = ChatOpenAI(api_key=settings.openai_api_key, model="gpt-4o-mini", temperature=0)
    tools = [get_run_sql_tool(), get_run_python_tool(), get_make_chart_tool()]
    agent = create_tool_calling_agent(llm=llm, tools=tools, prompt=prompt)
    executor = AgentExecutor(agent=agent, tools=tools, verbose=False)
    result = executor.invoke({"input": question})
    return {
        "answer": str(result.get("output", "")),
        "sql": "Generated by agent via run_sql tool",
    }
